# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-25 07:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0004_auto_20171025_1114'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='account_no',
            field=models.CharField(editable=False, max_length=200),
        ),
    ]
