# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-25 08:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0005_auto_20171025_1247'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='balance',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Balance'),
        ),
    ]
