# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-25 12:28
from __future__ import unicode_literals

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('transaction', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='transaction_id',
            field=models.CharField(default=django.utils.timezone.now, editable=False, max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='transaction',
            name='amount',
            field=models.DecimalField(decimal_places=2, editable=False, max_digits=20),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='current_balance',
            field=models.DecimalField(decimal_places=2, editable=False, max_digits=20),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='previous_balance',
            field=models.DecimalField(decimal_places=2, editable=False, max_digits=20),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='transaction_time',
            field=models.DateTimeField(default=datetime.datetime.now, editable=False),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='user',
            field=models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
