# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-26 05:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transaction', '0003_auto_20171025_1809'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='type',
            field=models.CharField(choices=[('Withdrawal', 'Withdrawal'), ('Deposit', 'Deposit'), ('Account Transfer', 'Account Transfer')], default='W', max_length=1),
            preserve_default=False,
        ),
    ]
