# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-26 05:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transaction', '0004_transaction_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='type',
            field=models.CharField(choices=[('Withdrawal', 'Withdrawal'), ('Deposit', 'Deposit'), ('Account Transfer', 'Account Transfer')], max_length=50),
        ),
    ]
